In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np


### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [30]:
#A1

a= np.array([[1,2,3,4,5],[2,4,5,8,10],[3,6,9,12,15],[4,8,12,16,20],[5,10,15,20,25]])

a.shape   #function used to total the number of columns and row (row,column)

(5, 5)

In [31]:
#A2
a.max()   #it is a method with an specific array to find its maximum value

np.int64(25)

In [32]:
#A3
np.max(a)   # it is a function that targets a specific array that being  a, the difference is that this function can any array like values/data

np.int64(25)

In [51]:
#B1
x=np.full((5,5), 1)   #it is a function used to create an array of a specified shape (as for my code it is 5x5 ) where every element is filled with the same value(as for my code it is 1)
print(x,'\n')         #prints what the array would look like
print(x.shape,'\n')   #prints the shape of the array
print(x.size,'\n')    #prints the size of the array
print(x.ndim,"\n")    #prints the number of dimension

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

(5, 5) 

25 

2 



In [39]:
#C
num = np.arange(-5,6) #It is a function that evenly spread the ranges between -5 and 6 (-5<x<6)
print(num)            #prints num
b=num*2               #multiplies the number by 2
print(b)              #Prints b

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[-10  -8  -6  -4  -2   0   2   4   6   8  10]


In [53]:
!mv '/content/drive/MyDrive/Colab Notebooks/NumphyExer.ipynb' '/content/drive/MyDrive/ColabNotebooks/IS110_Bperformance_Clarito/IS110_repo_Clarito/pythonEnvi_Clarito/NUMPHY_EXERCISE'

mv: cannot stat '/content/drive/MyDrive/Colab Notebooks/NumphyExer.ipynb': No such file or directory


In [54]:
!mv '/content/drive/MyDrive/Colab Notebooks/Copy of 05 NumPy for Numerical Computing.ipynb' '/content/drive/MyDrive/ColabNotebooks/IS110_Bperformance_Clarito/IS110_repo_Clarito/pythonEnvi_Clarito/NUMPHY_EXERCISE'